### ISSUE TITLE
Slack invite link is no longer active

### ISSUE THREAD

**Issue by mnasiadka** [tungstenfabric/website#41]
Slack invite link on the community subpage is no longer active.

**Comment by vmbrasseur** [comment]
Here's the link in question: https://tungsten.io/slack. It redirects to [the invite link](https://tungstenfabric.slack.com/join/shared_invite/enQtMzM0MjMyMDIzMzk3LTZjM2JmMWZlOGMyM2RlZDAxM2RiYjE0YWZlMTAyYWIzYmNmYmY4MTc5MzIzNjk5YWY2N2JmNzIzNzJlZmMzMzU), which results in this:

<img width="1460" alt="Screen Shot 2019-10-01 at 06 39 43" src="https://user-images.githubusercontent.com/298927/65967369-57810f00-e416-11e9-9c1a-8ddeb6558eba.png">

I'm not at my work computer now, so I can't create a new invite link at the moment but I'll do it later today.

Thanks for finding this, @mnasiadka!

**Comment by vmbrasseur** [comment]
The new link will be: https://join.slack.com/t/tungstenfabric/shared_invite/enQtMzM0MjMyMDIzMzk3LTZmY2FmY2JlZmRjN2YxMzgyOTNkNDZiNTRiYWU0NTRmNzI3N2RjMDIwY2UxZDlkODgzZDE0YzQ3MTlhNTg0N2I
