### ISSUE TITLE
carbide instructions missing AWS SG update for k8s GUI port 8443

### ISSUE THREAD

**Issue by qarham** [tungstenfabric/website#7]
Hi Team,

While testing TF carbide today, I faced an issue in opening k8s GUI on port 8443 "https://ec2-34-220-203-127.us-west-2.compute.amazonaws.com:8443", there was no response from the server side and HTTPS port 8443 request was not reaching at the node hosting k8s dashboard POD.  The issue is fixed after adding a rule in TF-SecurityGroup for port 8443 in the inbound direction. Please update the instructions for K8s GUI access accordingly or create TF-SG with the inbound rule for port 8443.

Thanks & Best Regards,
Qasim

**Comment by e-kuznetsov** [comment]
Inbound rule for port 8443 has been created. The issue can be closed.

**Comment by qarham** [comment]
Thanks, e-kuznetsov. Yes, I tested today and it's working.
