### ISSUE TITLE
Update CentOS AMI ID - Fix API: ec2:RunInstances Not authorized for images: [ami-4bf3d731]

### ISSUE THREAD

**Issue by DavidFlamini** [tungstenfabric/website#8]
Hi guys, the CentOS AMI ID changed (at least for us-east-1)

New CentOS AMI ID: ami-9887c6e7

This fixes the following error during stack deployment:

API: ec2:RunInstances Not authorized for images: [ami-4bf3d731]

Sorry, forgot the reference: https://github.com/tungstenfabric/website/wiki/Tungsten-Fabric:-10-minute-deployment-with-k8s-on-AWS

**Comment by e-kuznetsov** [comment]
Hi, David.
This CF template is currently not supported, please follow the instruction	https://tungstenfabric.github.io/website/Tungsten-Fabric-15-minute-deployment-with-k8s-on-AWS.html

@jameskellynet, I think we need to hide this old page to avoid confusion.

**Comment by DavidFlamini** [comment]
Since this is still open, quick question, where's the source of Contrail and container Dockerfiles, etc. been relocated? We have our own internal registry but we wanted to get the new code to try some fixes. Thanks!

**Comment by e-kuznetsov** [comment]
You can start here: https://github.com/Juniper/contrail-dev-env

**Comment by DavidFlamini** [comment]
Thanks!

**Comment by pcarver** [comment]
Can we close this issue?

**Comment by DavidFlamini** [comment]
yes, thank you
