### ISSUE TITLE
Website not showing MD properly

### ISSUE THREAD

**Issue by acinwinstack** [tungstenfabric/website#9]
As shown in screenshots, the the CLI command shown on [website](https://tungstenfabric.github.io/website/Tungsten-Fabric-one-line-install-on-k8s.html) is incorrect. Probably just a formatting issue.

![Github Markdown](https://user-images.githubusercontent.com/29940671/44378836-b1d24f80-a535-11e8-82cc-7fb976f8c12e.png)
![Actual Website](https://user-images.githubusercontent.com/29940671/44378837-b26ae600-a535-11e8-8294-51efa100ae22.png)

**Comment by tnaganawa** [comment]
Yeah, perhaps it needs {% raw %} tag.
https://stackoverflow.com/questions/24102498/escaping-double-curly-braces-inside-a-markdown-code-block-in-jekyll

I'll try this in my cloned repo on this weekend, and create PR if it's ok :)
